"""added student , grade and class tables

Revision ID: 4fddaa72f361
Revises: dec231046512
Create Date: 2024-06-17 17:11:22.689306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fddaa72f361'
down_revision: Union[str, None] = 'dec231046512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Students', sa.Column('Date_of_birth', sa.Date(), nullable=True))
    op.drop_column('Students', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Students', sa.Column('address', sa.DATE(), nullable=True))
    op.drop_column('Students', 'Date_of_birth')
    # ### end Alembic commands ###
