"""updated  student , so grades has a relationship with grade

Revision ID: 6356a702310e
Revises: 6ce70b79455e
Create Date: 2024-06-18 10:49:43.347180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6356a702310e'
down_revision: Union[str, None] = '6ce70b79455e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
